version: "3"

services:
  app:
    container_name: front-end-challenge-codesh
    image: front-end-challenge-codesh:prod
    user: node
    build:
      context: .
      dockerfile: dockerfile
    tty: true
    volumes:
      - .:/home/node
    ports:
      - 5010:5010